// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using VUniBox.Models;

namespace VUniBox.DBContext;

public partial class VUniBoxContext : DbContext
{
    public VUniBoxContext()
    {
    }

    public VUniBoxContext(DbContextOptions<VUniBoxContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Citations> Citations { get; set; }

    public virtual DbSet<DocumentStorage> DocumentStorage { get; set; }

    public virtual DbSet<Documents> Documents { get; set; }

    public virtual DbSet<OtpToken> OtpToken { get; set; }

    public virtual DbSet<Payments> Payments { get; set; }

    public virtual DbSet<Plans> Plans { get; set; }

    public virtual DbSet<Subscriptions> Subscriptions { get; set; }

    public virtual DbSet<UsageStats> UsageStats { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Citations>(entity =>
        {
            entity.HasKey(e => e.CitationId).HasName("PK__Citation__EAD2AD1B5DCB5C64");

            entity.Property(e => e.CitationId).HasColumnName("CitationID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DocumentId).HasColumnName("DocumentID");
            entity.Property(e => e.Style).HasMaxLength(50);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Document).WithMany(p => p.Citations)
                .HasForeignKey(d => d.DocumentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Citations__Docum__5AEE82B9");

            entity.HasOne(d => d.User).WithMany(p => p.Citations)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Citations__UserI__5BE2A6F2");
        });

        modelBuilder.Entity<DocumentStorage>(entity =>
        {
            entity.HasKey(e => e.DocumentStorageId).HasName("PK__Document__7381F341B105D5BF");

            entity.Property(e => e.DocumentStorageId).HasColumnName("DocumentStorageID");
            entity.Property(e => e.AuthorName).HasMaxLength(255);
            entity.Property(e => e.CitationStyle).HasMaxLength(50);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DocumentId).HasColumnName("DocumentID");
            entity.Property(e => e.FavoriteFlag).HasDefaultValue(false);
            entity.Property(e => e.FileName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.FilePath)
                .IsRequired()
                .HasMaxLength(1000);
            entity.Property(e => e.FileType).HasMaxLength(50);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Document).WithMany(p => p.DocumentStorage)
                .HasForeignKey(d => d.DocumentId)
                .HasConstraintName("FK__DocumentS__Docum__5629CD9C");

            entity.HasOne(d => d.User).WithMany(p => p.DocumentStorage)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__DocumentS__UserI__571DF1D5");
        });

        modelBuilder.Entity<Documents>(entity =>
        {
            entity.HasKey(e => e.DocumentId).HasName("PK__Document__1ABEEF6F7A53CBE8");

            entity.Property(e => e.DocumentId).HasColumnName("DocumentID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ExpiryDate).HasColumnType("datetime");
            entity.Property(e => e.FilePath).HasMaxLength(500);
            entity.Property(e => e.SourceUrl)
                .HasMaxLength(500)
                .HasColumnName("SourceURL");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .HasDefaultValue("Saved");
            entity.Property(e => e.Title).HasMaxLength(255);
            entity.Property(e => e.Type).HasMaxLength(20);
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.Documents)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Documents__UserI__5070F446");
        });

        modelBuilder.Entity<OtpToken>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OtpToken__3214EC074A498A17");

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Token)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.Used).HasDefaultValue(false);

            entity.HasOne(d => d.User).WithMany(p => p.OtpToken)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__OtpToken__UserId__06CD04F7");
        });

        modelBuilder.Entity<Payments>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("PK__Payments__9B556A587735F431");

            entity.Property(e => e.PaymentId).HasColumnName("PaymentID");
            entity.Property(e => e.Amount).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.PaidAt).HasColumnType("datetime");
            entity.Property(e => e.PayOsTransactionId)
                .HasMaxLength(100)
                .HasColumnName("PayOS_TransactionID");
            entity.Property(e => e.PaymentStatus)
                .HasMaxLength(20)
                .HasDefaultValue("Pending");
            entity.Property(e => e.PlanId).HasColumnName("PlanID");
            entity.Property(e => e.QrcodeUrl)
                .HasMaxLength(500)
                .HasColumnName("QRCodeURL");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Plan).WithMany(p => p.Payments)
                .HasForeignKey(d => d.PlanId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Payments__PlanID__4316F928");

            entity.HasOne(d => d.User).WithMany(p => p.Payments)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Payments__UserID__4222D4EF");
        });

        modelBuilder.Entity<Plans>(entity =>
        {
            entity.HasKey(e => e.PlanId).HasName("PK__Plans__755C22D75DE8E46E");

            entity.Property(e => e.PlanId).HasColumnName("PlanID");
            entity.Property(e => e.DurationMonths).HasDefaultValue(1);
            entity.Property(e => e.PlanName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Price).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.StorageLimitMb).HasColumnName("StorageLimitMB");
        });

        modelBuilder.Entity<Subscriptions>(entity =>
        {
            entity.HasKey(e => e.SubscriptionId).HasName("PK__Subscrip__9A2B24BD00DB7446");

            entity.Property(e => e.SubscriptionId).HasColumnName("SubscriptionID");
            entity.Property(e => e.PaymentId).HasColumnName("PaymentID");
            entity.Property(e => e.PlanId).HasColumnName("PlanID");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .HasDefaultValue("Active");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Payment).WithMany(p => p.Subscriptions)
                .HasForeignKey(d => d.PaymentId)
                .HasConstraintName("FK__Subscript__Payme__49C3F6B7");

            entity.HasOne(d => d.Plan).WithMany(p => p.Subscriptions)
                .HasForeignKey(d => d.PlanId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Subscript__PlanI__48CFD27E");

            entity.HasOne(d => d.User).WithMany(p => p.Subscriptions)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Subscript__UserI__47DBAE45");
        });

        modelBuilder.Entity<UsageStats>(entity =>
        {
            entity.HasKey(e => e.StatId).HasName("PK__UsageSta__3A162D1EBC24A9BE");

            entity.Property(e => e.StatId).HasColumnName("StatID");
            entity.Property(e => e.ChatbotUsed).HasDefaultValue(0);
            entity.Property(e => e.CitationUsed).HasDefaultValue(0);
            entity.Property(e => e.LastUpdated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.StorageUsedMb)
                .HasDefaultValue(0)
                .HasColumnName("StorageUsedMB");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.UsageStats)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__UsageStat__UserI__628FA481");
        });

        modelBuilder.Entity<Users>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CCACB9BE558D");

            entity.HasIndex(e => e.Email, "UQ__Users__A9D1053421A15FA9").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CurrentPlanId).HasColumnName("CurrentPlanID");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.FullName).HasMaxLength(255);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.IsVerified).HasDefaultValue(false);
            entity.Property(e => e.PasswordHash).HasMaxLength(255);

            entity.HasOne(d => d.CurrentPlan).WithMany(p => p.Users)
                .HasForeignKey(d => d.CurrentPlanId)
                .HasConstraintName("FK__Users__CurrentPl__3C69FB99");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}