// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VUniBox.Models;

public partial class Citations
{
    public int CitationId { get; set; }

    public int DocumentId { get; set; }

    public int UserId { get; set; }

    public string Style { get; set; }

    public string FormattedCitation { get; set; }

    public string InTextCitation { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Documents Document { get; set; }

    public virtual Users User { get; set; }
}