// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace VUniBox.Models;

public partial class DocumentStorage
{
    public int DocumentStorageId { get; set; }

    public int DocumentId { get; set; }

    public int UserId { get; set; }

    public string FileName { get; set; }

    public string FilePath { get; set; }

    public string Title { get; set; }

    public string AuthorName { get; set; }

    public int? PublicYear { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string CitationStyle { get; set; }

    public long? FileSize { get; set; }

    public string FileType { get; set; }

    public bool? FavoriteFlag { get; set; }

    public string Authors { get; set; }

    public DateOnly? PublicationDate { get; set; }

    public string Publisher { get; set; }

    public string Journal { get; set; }

    public string Volume { get; set; }

    public string Issue { get; set; }

    public string Pages { get; set; }

    public string Doi { get; set; }

    public string Isbn { get; set; }

    public string Abstract { get; set; }

    public string Description { get; set; }

    public string Keywords { get; set; }

    public string Subject { get; set; }

    public string Source { get; set; }

    public string Language { get; set; }

    public DateTime? RetrievedDate { get; set; }

    [JsonIgnore]
    public virtual Documents Document { get; set; }

    [JsonIgnore]
    public virtual Users User { get; set; }
}