// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VUniBox.Models;

public partial class DocumentStorage
{
    public int DocumentStorageId { get; set; }

    public int DocumentId { get; set; }

    public int UserId { get; set; }

    public string FileName { get; set; }

    public string FilePath { get; set; }

    public string Title { get; set; }

    public string AuthorName { get; set; }

    public int? PublicYear { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string CitationStyle { get; set; }

    public long? FileSize { get; set; }

    public string FileType { get; set; }

    public bool? FavoriteFlag { get; set; }

    public virtual Documents Document { get; set; }

    public virtual Users User { get; set; }
}