// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VUniBox.Models;

public partial class Documents
{
    public int DocumentId { get; set; }

    public int UserId { get; set; }

    public string Title { get; set; }

    public string FilePath { get; set; }

    public string SourceUrl { get; set; }

    public string Type { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public virtual ICollection<Citations> Citations { get; set; } = new List<Citations>();

    public virtual ICollection<DocumentStorage> DocumentStorage { get; set; } = new List<DocumentStorage>();

    public virtual Users User { get; set; }
}