// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace VUniBox.Models;

public partial class Documents
{
    public int DocumentId { get; set; }

    public int UserId { get; set; }

    public string Title { get; set; }

    public string FilePath { get; set; }

    public string SourceUrl { get; set; }

    public string Type { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public string Author { get; set; }

    public string Authors { get; set; }

    public DateOnly? PublicationDate { get; set; }

    public string Publisher { get; set; }

    public string Journal { get; set; }

    public string Volume { get; set; }

    public string Issue { get; set; }

    public string Pages { get; set; }

    public string Doi { get; set; }

    public string Isbn { get; set; }

    public string Abstract { get; set; }

    public string Description { get; set; }

    public string Keywords { get; set; }

    public string Subject { get; set; }

    public string Source { get; set; }

    public string Language { get; set; }

    public DateTime? RetrievedDate { get; set; }

    [JsonIgnore]
    public virtual ICollection<Citations> Citations { get; set; } = new List<Citations>();

    [JsonIgnore]
    public virtual ICollection<DocumentStorage> DocumentStorage { get; set; } = new List<DocumentStorage>();

    [JsonIgnore]
    public virtual Users User { get; set; }
}