// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VUniBox.Models;

public partial class OtpToken
{
    public int Id { get; set; }

    public string Email { get; set; }

    public string Token { get; set; }

    public DateTime? CreatedAt { get; set; }

    public bool? Used { get; set; }

    public int? UserId { get; set; }

    public virtual Users User { get; set; }
}