// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VUniBox.Models;

public partial class Payments
{
    public int PaymentId { get; set; }

    public int UserId { get; set; }

    public int PlanId { get; set; }

    public string PayOsTransactionId { get; set; }

    public string QrcodeUrl { get; set; }

    public decimal Amount { get; set; }

    public string PaymentStatus { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? PaidAt { get; set; }

    public virtual Plans Plan { get; set; }

    public virtual ICollection<Subscriptions> Subscriptions { get; set; } = new List<Subscriptions>();

    public virtual Users User { get; set; }
}