// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VUniBox.Models;

public partial class Plans
{
    public int PlanId { get; set; }

    public string PlanName { get; set; }

    public int StorageLimitMb { get; set; }

    public int CitationLimit { get; set; }

    public int ChatbotLimit { get; set; }

    public decimal Price { get; set; }

    public int? DurationMonths { get; set; }

    public virtual ICollection<Payments> Payments { get; set; } = new List<Payments>();

    public virtual ICollection<Subscriptions> Subscriptions { get; set; } = new List<Subscriptions>();

    public virtual ICollection<Users> Users { get; set; } = new List<Users>();
}