// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VUniBox.Models;

public partial class Subscriptions
{
    public int SubscriptionId { get; set; }

    public int UserId { get; set; }

    public int PlanId { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public string Status { get; set; }

    public int? PaymentId { get; set; }

    public virtual Payments Payment { get; set; }

    public virtual Plans Plan { get; set; }

    public virtual Users User { get; set; }
}