// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VUniBox.Models;

public partial class UsageStats
{
    public int StatId { get; set; }

    public int UserId { get; set; }

    public int? StorageUsedMb { get; set; }

    public int? CitationUsed { get; set; }

    public int? ChatbotUsed { get; set; }

    public DateTime? LastUpdated { get; set; }

    public virtual Users User { get; set; }
}