// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VUniBox.Models;

public partial class Users
{
    public int UserId { get; set; }

    public string FullName { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? CurrentPlanId { get; set; }

    public DateOnly? PlanExpiryDate { get; set; }

    public int Role { get; set; }

    public bool? IsVerified { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<Citations> Citations { get; set; } = new List<Citations>();

    public virtual Plans CurrentPlan { get; set; }

    public virtual ICollection<DocumentStorage> DocumentStorage { get; set; } = new List<DocumentStorage>();

    public virtual ICollection<Documents> Documents { get; set; } = new List<Documents>();

    public virtual ICollection<Payments> Payments { get; set; } = new List<Payments>();

    public virtual ICollection<Subscriptions> Subscriptions { get; set; } = new List<Subscriptions>();

    public virtual ICollection<UsageStats> UsageStats { get; set; } = new List<UsageStats>();
}